export * from "./hero";
export * from "./layout";
export * from "./page";
export * from "./pricing";
export * from "./online-course";
export * from "./why-choose-us";
export * from "./login/page";
export * from "./signup/page";
export * from "./test/page";
